param([string]$PublicUrl, [string]$GoogleVerification)
$ErrorActionPreference='Stop'
$root=Split-Path $PSScriptRoot -Parent
$utf8=[Text.UTF8Encoding]::new($false)
function Write-File($path,$text){[IO.File]::WriteAllText((Join-Path $root $path),$text,$utf8)}
$config=Get-Content (Join-Path $root 'config/site.json') -Raw -Encoding UTF8|ConvertFrom-Json
if($PSBoundParameters.ContainsKey('PublicUrl')){
 $uri=[Uri]$PublicUrl
 if(!$uri.IsAbsoluteUri -or $uri.Scheme -ne 'https' -or $uri.Query -or $uri.Fragment -or $uri.UserInfo){throw 'PublicUrl must be an absolute HTTPS URL without query, fragment or credentials.'}
 $config.publicUrl=$uri.AbsoluteUri.TrimEnd('/')+'/'
 $config.domainStatus='configured'
}
if($PSBoundParameters.ContainsKey('GoogleVerification')){
 if($GoogleVerification -and $GoogleVerification -notmatch '^[A-Za-z0-9_-]+$'){throw 'Invalid Google verification token.'}
 $config.googleVerification=$GoogleVerification
}
$url=$config.publicUrl
$base=[Uri]$url
$title=[Net.WebUtility]::HtmlEncode($config.title)
$description=[Net.WebUtility]::HtmlEncode($config.description)
$csp=(Get-Content (Join-Path $root 'config/security-policy.txt') -Raw -Encoding UTF8).Trim()
$identity=[ordered]@{'@context'='https://schema.org';'@type'='Person';'@id'=($url+'#person');name='Diego Pérez Obrero';url=$url;image=($url+'assets/responsive/about-polaroid-800.webp');jobTitle='Graphic designer, software developer and Lead Standby Motion Graphics operator';email='mailto:diegoperezobrero@gmail.com';knowsAbout=@('Graphic props for film and television','Digital props','Fake user interface (FUI)','On-set playback','Motion graphics')}
$json=$identity|ConvertTo-Json -Depth 5 -Compress
$verify=if($config.googleVerification){'  <meta name="google-site-verification" content="'+$config.googleVerification+'">'}else{'  <!-- Search Console verification awaits the chosen domain and ownership token. -->'}
$head=@"
<!-- SITE CONFIG START: generated by scripts/configure-site.ps1 -->
  <meta http-equiv="Content-Security-Policy" content="$csp">
  <meta name="referrer" content="strict-origin-when-cross-origin">
  <title>$title</title>
  <meta name="description" content="$description">
  <meta name="robots" content="index,follow,max-image-preview:large">
  <meta name="theme-color" content="#e9e7df">
  <link rel="canonical" href="$url">
  <link rel="icon" href="assets/favicon.svg" type="image/svg+xml">
  <meta property="og:type" content="website">
  <meta property="og:locale" content="en_GB">
  <meta property="og:site_name" content="Diego Pérez Obrero">
  <meta property="og:title" content="$title">
  <meta property="og:description" content="$description">
  <meta property="og:url" content="$url">
  <meta property="og:image" content="${url}assets/social-card.jpg">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta property="og:image:alt" content="Diego Pérez Obrero — Art, Digital Props and FUI for film and television">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="$title">
  <meta name="twitter:description" content="$description">
  <meta name="twitter:image" content="${url}assets/social-card.jpg">
$verify
  <script type="application/ld+json">$json</script>
<!-- SITE CONFIG END -->
"@
$html=Get-Content (Join-Path $root 'index.html') -Raw -Encoding UTF8
if($html.Contains('<!-- SITE CONFIG START:')){
 $html=[regex]::Replace($html,'(?s)<!-- SITE CONFIG START:.*?<!-- SITE CONFIG END -->',[Text.RegularExpressions.MatchEvaluator]{param($m) $head})
}else{
 $html=[regex]::Replace($html,'\s*<meta name="description"[^>]+>','')
 $html=[regex]::Replace($html,'\s*<meta name="theme-color"[^>]+>','')
 $html=[regex]::Replace($html,'<title>[^<]*</title>','')
 $html=$html.Replace('<head>','<head>' + "`n" + $head)
}
$html=[regex]::Replace($html,'\s*<meta charset="UTF-8">','')
$html=$html.Replace('<head>','<head>'+"`n"+'  <meta charset="UTF-8">')
Write-File 'index.html' $html
Write-File 'config/site.json' (($config|ConvertTo-Json)+"`n")
Write-File 'robots.txt' "User-agent: *`nAllow: /`nSitemap: ${url}sitemap.xml`n"
Write-File 'sitemap.xml' "<?xml version=`"1.0`" encoding=`"UTF-8`"?>`n<urlset xmlns=`"http://www.sitemaps.org/schemas/sitemap/0.9`"><url><loc>$([Net.WebUtility]::HtmlEncode($url))</loc></url></urlset>`n"
Write-File '.nojekyll' ''
$notFound=@"
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,follow"><meta name="referrer" content="strict-origin-when-cross-origin"><meta http-equiv="Content-Security-Policy" content="$csp"><title>Scene not found — Diego Pérez Obrero</title><style>html{background:#e9e7df;color:#24251f;font-family:Arial,Helvetica,sans-serif}body{max-width:820px;margin:12vh auto;padding:24px}small{font:13px 'Courier New',monospace}h1{font-size:clamp(44px,8vw,96px);font-weight:400;letter-spacing:-.05em;margin:.6em 0}i{font-family:Georgia,serif}p{max-width:50ch;line-height:1.6}a{color:inherit;display:inline-block;padding:14px 0;margin-right:24px;text-underline-offset:5px;overflow-wrap:anywhere}a:focus-visible{outline:2px solid;outline-offset:4px}nav{border-top:1px solid;margin-top:40px}</style></head><body><small>404 / OUT OF FRAME</small><h1>This scene<br>is <i>missing.</i></h1><p>The page may have moved, or the address may be incomplete. You can return to the portfolio or get in touch.</p><nav aria-label="Recovery links"><a href="$url">Back to the portfolio ↗</a><a href="mailto:diegoperezobrero@gmail.com">diegoperezobrero@gmail.com</a></nav></body></html>
"@
Write-File '404.html' $notFound
$headers=@"
/*
  Content-Security-Policy: $csp; frame-ancestors 'self'
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=()
  X-Frame-Options: SAMEORIGIN
  Strict-Transport-Security: max-age=31536000
"@
Write-File '_headers' $headers
$game=Get-Content (Join-Path $root 'games/ship-explorer/index.html') -Raw -Encoding UTF8
$game=[regex]::Replace($game,'<meta http-equiv="Content-Security-Policy"[^>]+>','')
$game=$game.Replace('<meta charset="utf-8">','<meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="'+$csp+'"><meta name="robots" content="noindex">')
$game=[regex]::Replace($game,'(?:<meta name="robots" content="noindex">){2,}','<meta name="robots" content="noindex">')
Write-File 'games/ship-explorer/index.html' $game
Write-Output "Metadata, sitemap, robots and 404 generated for $url"
if(!$config.googleVerification){Write-Output 'Search Console: ownership verification is still pending.'}
